### ISSUE TITLE
Unwrapping fields with custom scalars does not add the import

### ISSUE THREAD

**Issue by bombsimon** [mirumee/ariadne-codegen#153]
It seems like I missed a case when using the `ShorterResultsPlugin` and the unwrapped field contains a custom scalar type. In this situation the type does not get imported.

```graphql
# schema.graphql
scalar MyScalar

type Query {
  getScalar: MyScalar!
}

# queries.graphql
query TestQuery {
  getScalar
}
```

```toml
# pyproject.toml
[tool.ariadne-codegen]
plugins = ["ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin"]

[tool.ariadne-codegen.scalars.MyScalar]
type = "scalars.MyScalar"
```

```python
# scalars.py
MyScalar = dict
```

Will generate `client.py`:

```python
async def test_query(self) -> MyScalar
```

But `MyScalar` will not be imported to `client.py`.

It does work for input types so doing something like this will import the scalar:

```graphql
# schema.graphql
type Query {
  getScalar(input: MyScalar!): MyScalar!
}

# queries.graphql
query TestQuery($input: MyScalar!) {
  getScalar(input: $input)
}
```

I'll debug this and file a PR as soon as I find the root cause.
