### ISSUE TITLE
Client methods for queries and mutation names do not respect `convert_to_snake_case = false`

### ISSUE THREAD

**Issue by nocnokneo** [mirumee/ariadne-codegen#275]
With config like:

```toml
[tool.ariadne-codegen]
# ...
convert_to_snake_case = false
plugins = ["ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin"]
async_client = false
```

And a mutation like:

```graphql
mutation createGroup($group: CreateGroupInput!) {
    createGroup(group: $group) {
        ...GroupFragment
    }
}
```

I get a `Client` method:

```py
def create_group(...)
```
