### ISSUE TITLE
[Feature request] Multiple clients

### ISSUE THREAD

**Issue by pkucmus** [mirumee/ariadne-codegen#310]
Right now we can generate only one client for one GQL server. Could we add an ability to setup multiple? Not sure how would that look like in TOML but maybe:

```toml
[[tool.ariadne-codegen.saleor]]
remote_schema_url = "https://my.saleor.com"
queries_path = "saleor/queries.graphql"
target_package_name = "saleor_client"

[[tool.ariadne-codegen.my_app]]
remote_schema_url = "https://my.app.com"
queries_path = "my_app/queries.graphql"
target_package_name = "my_app_client"
```
